import Image from 'next/image';


export default function Head() {
  return (
    <>    
    
      <title>Placa Mãe</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
     
      
    </>
  );
  
}
